### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by dsyme** [isaksky/Incremental.NET#1]
Hi @isaksky 

This is a really interesting library, relevant to https://github.com/fsprojects/Fabulous/issues/258 and possibly many other applications.

Do you think we could move this to "fsprojects" to put it on a sustainable joint development path?  I'd be interested in contributing long term

thanks
don

**Comment by isaksky** [comment]
Yea, no problem. Sounds good!

**Comment by dsyme** [comment]
Cool, I've invited you to the org, after you accept that you should be able to move the repo.  Let me know when you've done that!

thanks
don

**Comment by isaksky** [comment]
Ok, this is done.

**Comment by nightroman** [comment]
Out of curiosity, what was the outcome?
